name: Upload File Plugins Release Process

on:
  workflow_dispatch:
    inputs:
      fileName:
        type: string
        description: File Name (ucv-ext-abc:1.0.0)
        required: true
      folderName:
        type: string
        description: Folder Name (ucv-ext-abc)
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check disk space
        run: df . -h
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Create Folder
        run: |
          sudo mkdir -p /mnt/docker/tmp
          echo "TMPDIR=/mnt/docker/tmp" >> $GITHUB_ENV
          sudo mv /var/lib/docker/tmp /mnt/docker/tmp.old || true
          sudo ln -s /mnt/docker/tmp /var/lib/docker/tmp
          sudo mkdir /mnt/docker/files
          sudo mkdir "/mnt/docker/files/${{ github.event.inputs.folderName }}"
      - name: Docker Pull Image
        run: |
          docker pull "urbancode/${{ github.event.inputs.fileName }}"
      - uses: actions/checkout@v3
      - name: Docker Save as TAR
        run: |
          df -h
          ls -ltra
          docker save -o "${{ github.event.inputs.fileName }}.tar" "urbancode/${{ github.event.inputs.fileName }}"
          ls -a
          sudo mkdir -p "/mnt/docker/files/${{ github.event.inputs.folderName }}"
          sudo mv "./${{ github.event.inputs.fileName }}.tar" "/mnt/docker/files/${{ github.event.inputs.folderName }}/"
          cd /mnt/docker/files/${{ github.event.inputs.folderName }}/
          ls -a
      - uses: edgarrc/action-7z@v1
        with:
          args: 7z a -v50m "/mnt/docker//${{ github.event.inputs.folderName }}/${{ github.event.inputs.fileName }}.tar.7z" "/mnt/docker//${{ github.event.inputs.folderName }}/${{ github.event.inputs.fileName }}.tar"
      - name: Commit changes
        run: |
          git init
          git config --global user.email "lalit-ku@hcl.com"
          git config --global user.name "lalitKumarHCL"
          git add *.00*
          git commit -m "adding ${{ github.event.inputs.fileName }}"
          git branch -M main
          git push -u origin main
          docker system prune -af --volumes
