name: Upload File Plugins Release Process

on:
  workflow_dispatch:
    inputs:
      fileName:
        type: string
        description: File Name
      folderName:
        type: string
        description: Folder Name
      fileName2:
        type: string
        description: File Name 2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Folder
        run: |
          mkdir files
          mkdir "files/${{ github.event.inputs.folderName }}"
      - uses: actions/checkout@v3
      - name: Docker Pull Image and Save as TAR
        run: |
          docker pull ${{ github.event.inputs.fileName }}
          docker save -o "${{ github.event.inputs.fileName2 }}.tar" ${{ github.event.inputs.fileName }}
          ls -a
          mv "./${{ github.event.inputs.fileName2 }}.tar" "files/${{ github.event.inputs.folderName }}/"
      - uses: edgarrc/action-7z@v1
        with:
          args: 7z a -v50m "{{ github.event.inputs.fileName2 }}.tar.7z" "${{ github.event.inputs.fileName2 }}.tar"
      - name: Commit changes
        run: |
          git init
          git config --global user.email "lalit-ku@hcl.com"
          git config --global user.name "lalitKumarHCL"
          git add *.7z
          git commit -m "adding ${{ github.event.inputs.fileName }}"
          git branch -M main
          git push -u origin main
